# Generated by Django 4.0.5 on 2022-06-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinichistory',
            name='active',
            field=models.BooleanField(blank=True, help_text='Field indicating if the current clinic history is active. It should be only one active and it should be the last one', null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the appointment was scheduled.', null=True, verbose_name='Scheduled'),
        ),
    ]
